In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('../data/raw/marketing_campaign.csv', sep='\t')
df

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,...,5,0,0,0,0,0,0,3,11,0
2236,4001,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,...,7,0,0,0,1,0,0,3,11,0
2237,7270,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,...,6,0,1,0,0,0,0,3,11,0
2238,8235,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,...,3,0,0,0,0,0,0,3,11,0
2239,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,...,7,0,0,0,0,0,0,3,11,1

In [3]:
inf_cols = df.isin([np.inf, -np.inf]).sum()
print(inf_cols[inf_cols > 0])

Series([], dtype: int64)

In [4]:
df['Education'].unique()
df['Marital_Status'].unique()

<StringArray>
['Single', 'Together', 'Married', 'Divorced', 'Widow', 'Alone', 'Absurd',
 'YOLO']
Length: 8, dtype: str

In [5]:
#Suppression des colonnes inutiles
df.drop(['ID','Z_CostContact','Z_Revenue'],axis = 1, inplace = True)
df

,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,...,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response
0,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,88,...,10,4,7,0,0,0,0,0,0,1
1,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,1,...,1,2,5,0,0,0,0,0,0,0
2,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,49,...,2,10,4,0,0,0,0,0,0,0
3,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,4,...,0,4,6,0,0,0,0,0,0,0
4,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,43,...,3,6,5,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,43,...,3,4,5,0,0,0,0,0,0,0
2236,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,0,...,2,5,7,0,0,0,1,0,0,0
2237,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,48,...,3,13,6,0,1,0,0,0,0,0
2238,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,30,...,5,10,3,0,0,0,0,0,0,0
2239,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,3,...,1,4,7,0,0,0,0,0,0,1

In [6]:
#Remplaçons year_birth par age
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'], format='%d-%m-%Y')
last_enrollment = df['Dt_Customer'].max()
df['Age'] = last_enrollment.year - df['Year_Birth']
df.drop('Year_Birth', axis=1, inplace=True)
df['Nb_Jours_Client'] = (last_enrollment - df['Dt_Customer']).dt.days
df.drop('Dt_Customer', axis=1, inplace=True)
df

,Education,Marital_Status,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response,Age,Nb_Jours_Client
0,Graduation,Single,58138.0,0,0,58,635,88,546,172,...,7,0,0,0,0,0,0,1,57,663
1,Graduation,Single,46344.0,1,1,38,11,1,6,2,...,5,0,0,0,0,0,0,0,60,113
2,Graduation,Together,71613.0,0,0,26,426,49,127,111,...,4,0,0,0,0,0,0,0,49,312
3,Graduation,Together,26646.0,1,0,26,11,4,20,10,...,6,0,0,0,0,0,0,0,30,139
4,PhD,Married,58293.0,1,0,94,173,43,118,46,...,5,0,0,0,0,0,0,0,33,161
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,Graduation,Married,61223.0,0,1,46,709,43,182,42,...,5,0,0,0,0,0,0,0,47,381
2236,PhD,Together,64014.0,2,1,56,406,0,30,0,...,7,0,0,0,1,0,0,0,68,19
2237,Graduation,Divorced,56981.0,0,0,91,908,48,217,32,...,6,0,1,0,0,0,0,0,33,155
2238,Master,Together,69245.0,0,1,8,428,30,214,80,...,3,0,0,0,0,0,0,0,58,156
2239,PhD,Married,52869.0,1,1,40,84,3,61,2,...,7,0,0,0,0,0,0,1,60,622

In [7]:
#création de la colonne Total_depenses
df['Total_depenses'] = (df['MntWines'] + df['MntFruits'] +
                        df['MntMeatProducts'] + df['MntFishProducts'] +
                        df['MntSweetProducts'] + df['MntGoldProds'])
df

,Education,Marital_Status,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,...,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response,Age,Nb_Jours_Client,Total_depenses
0,Graduation,Single,58138.0,0,0,58,635,88,546,172,...,0,0,0,0,0,0,1,57,663,1617
1,Graduation,Single,46344.0,1,1,38,11,1,6,2,...,0,0,0,0,0,0,0,60,113,27
2,Graduation,Together,71613.0,0,0,26,426,49,127,111,...,0,0,0,0,0,0,0,49,312,776
3,Graduation,Together,26646.0,1,0,26,11,4,20,10,...,0,0,0,0,0,0,0,30,139,53
4,PhD,Married,58293.0,1,0,94,173,43,118,46,...,0,0,0,0,0,0,0,33,161,422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,Graduation,Married,61223.0,0,1,46,709,43,182,42,...,0,0,0,0,0,0,0,47,381,1341
2236,PhD,Together,64014.0,2,1,56,406,0,30,0,...,0,0,0,1,0,0,0,68,19,444
2237,Graduation,Divorced,56981.0,0,0,91,908,48,217,32,...,0,1,0,0,0,0,0,33,155,1241
2238,Master,Together,69245.0,0,1,8,428,30,214,80,...,0,0,0,0,0,0,0,58,156,843
2239,PhD,Married,52869.0,1,1,40,84,3,61,2,...,0,0,0,0,0,0,1,60,622,172

In [8]:
#Encodage de education
df['Education'] = df['Education'].str.strip()
education_mapping = {
    'Basic'      : 0,
    '2n Cycle'   : 1,
    'Graduation' : 2,
    'Master'     : 3,
    'PhD'        : 4
}
df['Education'] = df['Education'].map(education_mapping)

In [9]:
#Encodage de Marital_Status
df['Marital_Status'] = df['Marital_Status'].str.strip()
marital_mapping = {
    'Single'   : 0,
    'Divorced' : 0,
    'Widow'    : 0,
    'Alone'    : 0,
    'Absurd'   : 0,
    'YOLO'     : 0,
    'Together' : 1,
    'Married'  : 1
}
df['Marital_Status'] = df['Marital_Status'].map(marital_mapping)

In [10]:
#Suppression des valeurs manquantes
df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)

In [11]:
#création de la feature Total_kids
df['Total_kids'] = df['Kidhome'] + df['Teenhome']

In [12]:
#création de la feature Total_purchases
df['Total_purchases'] = df['NumWebPurchases'] +df['NumStorePurchases']  + df['NumCatalogPurchases']
+ df['NumDealsPurchases']

0       3
1       2
2       1
3       2
4       5
       ..
2211    2
2212    7
2213    1
2214    2
2215    3
Name: NumDealsPurchases, Length: 2216, dtype: int64

In [13]:
#création des features depenses_moyenne_par_achat et tauc_de_reponse_aux_campagnes
df['Avg_spend_per_purchase'] = df.apply(
    lambda row: row['Total_depenses'] / row['Total_purchases'] 
    if row['Total_purchases'] > 0 else 0, axis=1
)
campagnes = ['AcceptedCmp1', 'AcceptedCmp2', 'AcceptedCmp3', 
             'AcceptedCmp4', 'AcceptedCmp5', 'Response']

df['Campaign_Response_Rate'] = df[campagnes].sum(axis=1) / len(campagnes)

In [14]:
#Suppression des colonnes Campagnes ainsi que les features Kidhome et Teenhome
campagnes = ['AcceptedCmp1', 'AcceptedCmp2', 'AcceptedCmp3', 
             'AcceptedCmp4', 'AcceptedCmp5', 'Response']
df.drop(campagnes,axis = 1, inplace = True)
df.drop(['Kidhome','Teenhome'],axis = 1, inplace = True)

In [15]:
df.to_csv('../data/processed/clean_marketing_campaign.csv', index=False)

In [16]:
scaler = StandardScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)
df_scaled.to_csv('../data/processed/scaled_marketing_campaign.csv', index=False)