In [103]:
#1.iMPORTATION DES BIBLIOTHÈQUES

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [104]:
#2. CHARGEMENT DU JEU DE DONNÉES

df = pd.read_csv("../data/raw/marketing_campaign.csv", sep="\t")
df

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,...,5,0,0,0,0,0,0,3,11,0
2236,4001,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,...,7,0,0,0,1,0,0,3,11,0
2237,7270,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,...,6,0,1,0,0,0,0,3,11,0
2238,8235,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,...,3,0,0,0,0,0,0,3,11,0
2239,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,...,7,0,0,0,0,0,0,3,11,1

In [106]:
#3.ENCODAGE EDUCATION ET SITUATION MARITALE

#encodage education

education_map = {
    'Basic'      : 0,
    '2n Cycle'   : 1,
    'Graduation' : 2,
    'Master'     : 3,
    'PhD'        : 4
}

df['Education'] =df['Education'].str.strip().map(education_map)

#encodage marital_status
marital_map = {
    'Single'   : 0,
    'Together' : 1,
    'Married'  : 1,
    'Divorced' : 0,
    'Widow'    : 0,
    'Alone'    : 0,
    'Absurd'   : 0,
    'YOLO'     : 0
}
df['Marital_Status']=df['Marital_Status'].map(marital_map)
df.shape

(2240, 29)

In [107]:
#4. CREATION DE LA COLONNE SOMME DEPENSES

df['Somme_depenses'] =df[['MntWines','MntFruits','MntMeatProducts','MntSweetProducts','MntGoldProds']].sum(axis=1)
print(df.shape)
df

(2240, 30)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Somme_depenses
0,5524,1957,2,0,58138.0,0,0,04-09-2012,58,635,...,0,0,0,0,0,0,3,11,1,1445
1,2174,1954,2,0,46344.0,1,1,08-03-2014,38,11,...,0,0,0,0,0,0,3,11,0,25
2,4141,1965,2,1,71613.0,0,0,21-08-2013,26,426,...,0,0,0,0,0,0,3,11,0,665
3,6182,1984,2,1,26646.0,1,0,10-02-2014,26,11,...,0,0,0,0,0,0,3,11,0,43
4,5324,1981,4,1,58293.0,1,0,19-01-2014,94,173,...,0,0,0,0,0,0,3,11,0,376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,2,1,61223.0,0,1,13-06-2013,46,709,...,0,0,0,0,0,0,3,11,0,1299
2236,4001,1946,4,1,64014.0,2,1,10-06-2014,56,406,...,0,0,0,1,0,0,3,11,0,444
2237,7270,1981,2,0,56981.0,0,0,25-01-2014,91,908,...,0,1,0,0,0,0,3,11,0,1209
2238,8235,1956,3,1,69245.0,0,1,24-01-2014,8,428,...,0,0,0,0,0,0,3,11,0,763
2239,9405,1954,4,1,52869.0,1,1,15-10-2012,40,84,...,0,0,0,0,0,0,3,11,1,170

In [108]:
#5. CREATION DE LA COLONNE AGE

# Format jour-mois-année
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'], format='%d-%m-%Y')

# Extraire la date max
date_max = df['Dt_Customer'].max()

# Calculer l'âge
df['Year_Birth'] = date_max.year - df['Year_Birth']

print(df.shape)
df.head()

(2240, 30)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Somme_depenses
0,5524,57,2,0,58138.0,0,0,2012-09-04,58,635,...,0,0,0,0,0,0,3,11,1,1445
1,2174,60,2,0,46344.0,1,1,2014-03-08,38,11,...,0,0,0,0,0,0,3,11,0,25
2,4141,49,2,1,71613.0,0,0,2013-08-21,26,426,...,0,0,0,0,0,0,3,11,0,665
3,6182,30,2,1,26646.0,1,0,2014-02-10,26,11,...,0,0,0,0,0,0,3,11,0,43
4,5324,33,4,1,58293.0,1,0,2014-01-19,94,173,...,0,0,0,0,0,0,3,11,0,376

In [109]:
#6. SUPPRESSION DES COLONNES INUTILES POUR NOTRE ANALYSE

#a.collection des différentes colonnes à supprimer
cols_a_supprimer = [

    'ID',            # identifiant non informatif
    'Z_Revenue',     # colonne constante inutile
    'Z_CostContact', # colonne constante inutile
]

#b.suppression effective de ces colonnes
df.drop(columns=cols_a_supprimer, inplace=True,errors='ignore')

#c.affichage et vérification
print(df.shape)

(2240, 27)

In [110]:
#7. CONVERSION DE DT_CUSTOMER EN NOMBRE DE JOURS DEPUIS L'INSCRIPTION

df['Dt_Customer'] =(date_max - df['Dt_Customer']).dt.days
print(df.shape)
df

(2240, 27)

,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,...,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response,Somme_depenses
0,57,2,0,58138.0,0,0,663,58,635,88,...,4,7,0,0,0,0,0,0,1,1445
1,60,2,0,46344.0,1,1,113,38,11,1,...,2,5,0,0,0,0,0,0,0,25
2,49,2,1,71613.0,0,0,312,26,426,49,...,10,4,0,0,0,0,0,0,0,665
3,30,2,1,26646.0,1,0,139,26,11,4,...,4,6,0,0,0,0,0,0,0,43
4,33,4,1,58293.0,1,0,161,94,173,43,...,6,5,0,0,0,0,0,0,0,376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,47,2,1,61223.0,0,1,381,46,709,43,...,4,5,0,0,0,0,0,0,0,1299
2236,68,4,1,64014.0,2,1,19,56,406,0,...,5,7,0,0,0,1,0,0,0,444
2237,33,2,0,56981.0,0,0,155,91,908,48,...,13,6,0,1,0,0,0,0,0,1209
2238,58,3,1,69245.0,0,1,156,8,428,30,...,10,3,0,0,0,0,0,0,0,763
2239,60,4,1,52869.0,1,1,622,40,84,3,...,4,7,0,0,0,0,0,0,1,170